# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppReview' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SQLite.swift', '~> 0.11.6'
  # Pods for AppReview

end
