# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Demo_Alamofire' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.7'
  # Pods for Demo_Alamofire

end
